title = "Gitleaks Config"

[extend]
useDefaultRules = true

[[allowlists]]
description = "Ignore known safe patterns"
regexes = [
  '''(?i)(com\.example\.|app\.example\.)''',
  '''(TEST_TOKEN|DUMMY_KEY|EXAMPLE_SECRET)''',
  '''(?i)dummy-never-match'''
]
