title = "Gitleaks Config"

[[allowlists]]
stopwords = []
description = "Allowlist for known false positives"

  [[allowlist.rules]]
  id = "ignore-bundle-ids"
  regex = '''(?i)(com\.example\.|app\.example\.)'''

  [[allowlist.rules]]
  id = "ignore-test-tokens"
  regex = '''(TEST_TOKEN|DUMMY_KEY|EXAMPLE_SECRET)'''

  [[allowlist.rules]]
  id = "ignore-never-match"
  regex = '''(?i)dummy-never-match'''
